name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint Code
        run: bun lint

      - name: Format Code
        run: bun format

      - name: Typechecking
        run: bun typecheck

      - name: Run Tests
        run: bun test
